### ISSUE TITLE
Should the mptl3.ppn be aligned with the mpt table size (16MB)?

### ISSUE THREAD

**Issue by rock-ifly** [riscv/riscv-smmtt#111]
**Should the mptL3 ppn  be aligned with the mpt table size?**

for MPTL3, the mptl3.ppn is the base addr for mptL2, which is size of 16MB, 

should the  mptl3.ppn be 

A : aligned with the mpt table size(16MB)?

B: or any addr without any alignment restriction?

**Comment by rsahita** [comment]
yes (A). the address of the table should be naturally aligned to the size of the table.  Will post a PR.

**Comment by rock-ifly** [comment]
OK.

Then we can see that, when PAW(physical address width) > 46
1) mptl3 is aligned to size of mptl3, which is determined by PAW. such as when PAW=48, mptl3 need to aligned with **4 Bytes**.
2) mptl2 is aligned to size of mptl2, which is **16MB**.
3) mptl2 is aligned to size of mptl1, which is **4KB**.

**Comment by rsahita** [comment]
Actually this is specified in Section 3.1
>The mmpt.PPN refers to an MPTL3 table or an MPTL2 table based on physical address width (PAW). For 56
>= PAW > 46, MPTL3 table must be of size 2^(PAW-43) bytes and naturally aligned to that sized byte
boundary. For 46 >= PAW > 32 the MPTL2 table must be of size 2^(PAW-22) bytes for Smmpt46 and Smmpt34,
and must be naturally aligned to that sized byte boundary. In these modes, the lowest two bits of
the physical page number (mmpt.PPN) in mmpt always read as zeros.

so for your example PAW of 48, mmpt.PPN will refer to a MPTL3 of size 2^5 bytes and aligned to that size, 
MPTL2 will refer to a table of size 16MB and aligned to that size, and MPTL3 will be a 4K table and aligned to that size.

**Comment by rock-ifly** [comment]
OK, thank you.

**Comment by SiFiveHolland** [comment]
> so for your example PAW of 48, mmpt.PPN will refer to a MPTL3 of size 2^5 bytes and aligned to that size

This is not correct. mmpt.PPN is a _physical page number_, not a _physical address_, so the minimum alignment is 4 KiB, regardless of the size of the table.

In fact, the last sentence from that paragraph implies the minimum alignment is 16 KiB (4 pages), even though I think it was meant to imply that the minimum alignment is 4 bytes (as it would imply if empt.PPN was an address).

**Comment by rsahita** [comment]
thanks for catching my error @SiFiveHolland - I misspoke - I meant that the actual entries may occupy less than the min 4KiB page for the L3 entries. thanks for the PR #112
