### ISSUE TITLE
Is `Svpams` an extension name?

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-smmtt#2]
As a person interested in this specification (as a developer once involved TEE), I'd like to prepare for it and found something not obvious from the documentation.

Considering from the CSR existence (16 CSRs allocated tentatively) and being dependent from `Smmtt`, `Svpams` looks like an extension.  However, the documentation does not refer `Svpams` as an extension.

If you have any free time, clarifying whether `Svpams` is an extension would be helpful.

**Comment by rsahita** [comment]
Yes - Svpams is an extension specified as part of the broader "Supervisor Domains" specification. I will make that clear in the next update of the specification soon.

**Comment by rsahita** [comment]
addressed in draft 1.0.2
