### ISSUE TITLE
Moving the ISA part of external debug security to smmtt

### ISSUE THREAD

**Issue by AoteJin** [riscv/riscv-smmtt#22]
Just as discussed in external debug TG meeting on Jan 30th, it is agreed to move the ISA part to smmtt spec. File the issue to track progress.

I think we need a chapter in smmtt to fit in and rephrase this part of external debug security draft
https://github.com/joxie/riscv-external-debug-security/blob/dev/chapter2.adoc

**Comment by AoteJin** [comment]
The message I received is different. I thought we agreed on moving ISA part to smmtt TG. @joxie and @gokhankaplayan to correct me.

Overall I think it is not a good idea to have two place separately document the ISA part of external debug security.

**Comment by rsahita** [comment]
it is natural to have common ISA parts required for external debug be in the external debug spec. We should add any extensions needed for supervisor domains in the supervisor domains spec. hope that makes sense.
