### ISSUE TITLE
Should mideleg[32] be hard-wired to 0 in Smsdia ?

### ISSUE THREAD

**Issue by gagachang** [riscv/riscv-smmtt#38]
According to Priv. Spec.: *Machine Trap Delegation Registers (medeleg and mideleg)*:
```
mideleg holds trap delegation bits for individual interrupts, with the layout of bits matching those
in the mip register (i.e., STIP interrupt delegation control is located in bit 5).
```

Per discussion in https://github.com/riscv/riscv-smmtt/issues/34.
We may not want to delegate `MSDEI` to less privilege mode.
If this is true, it's helpful to explicitly mention that `mideleg[32]` should be hard-wired to 0 if CPU supports `Smsdia`.

**Comment by ved-rivos** [comment]
Will add that `MSDEI` cannot be delegated.

**Comment by gagachang** [comment]
That's helpful, thanks!

**Comment by ved-rivos** [comment]
related to the issue #34 we will not hardwire mideleg[32] to 0. This interrupt will be renamed to SDEIP and can be delegated if needed to an SD.

**Comment by gagachang** [comment]
Close this issue, should be discussed in #34.
