### ISSUE TITLE
Missing glossary

### ISSUE THREAD

**Issue by xypron** [riscv/riscv-smmtt#42]
It would be helpful to have a glossary for the abbreviations used in this specification (e.g. TCB).

**Comment by rsahita** [comment]
ack. i will work on adding one.

**Comment by wmat** [comment]
Note that we are working to build a centralized glossary.  It can be found
here. https://github.com/riscv/riscv-glossary

**Comment by rsahita** [comment]
thanks @wmat - does it incorporate the terms from the one we have in the CoVE TG spec [here](https://github.com/riscv-non-isa/riscv-ap-tee/blob/main/specification/glossary.adoc )

**Comment by rsahita** [comment]
addressed in PR #47

**Comment by rsahita** [comment]
addressed in PR #47
