### ISSUE TITLE
MTT implicit accesses should be treated as M-mode accesses for purposes of PMP checking

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-smmtt#49]
Also, should add normative discussion of similar issues as occur for implicit accesses in virtual memory translation (PMAs, endianness, etc).

**Comment by rsahita** [comment]
I added text in PR #48 - will work on adding any other considerations

**Comment by rsahita** [comment]
@kasanovic ptal at PR #58

**Comment by rsahita** [comment]
closing - addressed in PR #58
