### ISSUE TITLE
A typo on page 17

### ISSUE THREAD

**Issue by zhuotianshu** [riscv/riscv-smmtt#57]
On page 17, the description of 1G_allow_r: 

> The 1G range of address is allowed (read only) for the domain. The INFO
> field must be 0. When configuring 1G ranges, RDSM ensures that 32 MTTL2
> entries, each corresponding to 32M of address space, have identical TYPE
> field values. The INFO field must be 0.

The last sentence "The INFO field must be 0." seems to be identical with the second sentence of this paragraph.

**Comment by rsahita** [comment]
thanks. addressed as part of PR #58
