### ISSUE TITLE
No possibility for sparse tables when using MTTL3

### ISSUE THREAD

**Issue by SiFiveHolland** [riscv/riscv-smmtt#64]
Section 4.1 claims that the MTT can be sparsely populated. However, the MTTL3 entry format (Figure 9) has no type field, which leaves no way to sparsely populate the MTTL3. The MTTL3 entry should have a type field, even if the only defined types are disallow/invalid and `MTT_L2_DIR`.

**Comment by rsahita** [comment]
addressed by PR #96
