### ISSUE TITLE
Should mttp.SDID be WARL? Can non-zero writes be ignored when mttp.MODE == Bare?

### ISSUE THREAD

**Issue by jackwdandrew** [riscv/riscv-smmtt#7]
1. An implementation may not implement all SDID domains, especially for larger SDIDLEN. Therefore, should we allow SDID to be WARL?

2. When mttp.MODE == 0, the spec currently states:

> In this case, the remaining fields (SDID, MTTPPN) in mttp must be set to zeros, else generate a fault. 

Can hardware force the other values to 0 when mttp.MODE== Bare such that a fault doesn't need to be generated?

**Comment by rsahita** [comment]
9-19 discussion: sufficient to return 0 for unused fields in cases BARE (and additional modes like PMP)

**Comment by jackwdandrew** [comment]
Closing as happy with @rsahita's explaination.
