### ISSUE TITLE
Does the physical address generated by page table walk need to be checked by MTT？

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-smmtt#99]
In spec，it is said, " it simply provides access permissions for the physically addressed region/page  (post any S-mode and/or G stage address translation) to enforce the isolation properties per the use case requirements".  
I am confused about whether  the physical address generated by page table walk need to be checked.

**Comment by ved-rivos** [comment]
I think the parenthetical should be removed. The MTT should be enforced on all implicit and explicit memory accesses when effective privilege mode of the access is less than M.

**Comment by rsahita** [comment]
This is in the non-normative section - fixing the description in an incoming PR with a reference to the normative section where the spec is clear in this aspect.

**Comment by rsahita** [comment]
@jinyinghan324 PTAL at PR #103

**Comment by jinyinghan324** [comment]
Thank you
